### ISSUE TITLE
[FEATURE REQUEST] Дополнительное поле в профиль

### ISSUE THREAD

**Issue by ZincLasagna** [ITMO-meet/frontend#60]
Я считаю что в каждом уважающем себя сайте знакомст должен быть пункт "Любимая вайфу" потому что амняме это огромная часть культуры итмо и мира в целом, тем более как понять совместим ли ты с человеком не зная его любимой вайфу, это очень важно и способно разрушать пары..... ( и я не про пары в вузах)

**Comment by graevsky** [comment]
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠿⠟⢛⣛⣛⣛⡛⠿⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠿⣛⣩⣵⣶⣿⣿⣿⣿⣿⣿⣿⣿⣶⣶⣭⣙⡻⠿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⢟⣩⣶⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣮⣙⠿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⣋⣴⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣮⡙⢿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⢋⠶⢛⣩⣵⢰⡶⣠⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡔⣶⡎⣙⠻⢿⣦⡙⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⡟⣰⢡⣾⣿⠟⡡⢊⣴⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣌⢣⠸⣿⣦⡹⣷⡘⣿⣿
⣿⣿⣿⣿⣿⣿⣿⡟⣴⣿⡘⢟⠁⢊⣴⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣧⡡⠘⣿⡇⣽⣿⠘⣿
⣿⣿⣿⣿⣿⣿⣿⢠⣿⣿⣿⣦⣶⣿⣿⣿⣿⣿⣿⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⢸⣿⣿⣿⣿⣿⣿⣷⣤⣭⣴⣿⣿⡇⣿
⣿⣿⣿⣿⣿⣿⡇⣾⣿⣿⣿⣿⡟⣻⣿⣿⣿⣿⡟⡈⣿⣿⣿⣿⣿⣿⣿⣿⢻⣿⠇⠸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡗⣿
⣿⣿⣿⣿⣿⣿⡇⣿⣿⣿⣿⣿⢹⣿⣿⡿⣿⣿⡇⣷⡸⣿⡏⣿⣿⣿⣿⣿⢸⡟⣼⡄⣿⡿⢫⣿⣿⣿⣿⣿⣿⣿⣿⣿⢸⣿
⣿⣿⣿⣿⣿⣿⣷⢹⣿⣿⣿⣿⢸⣿⣿⣷⢊⣙⢃⣉⡁⠈⠇⠘⣿⣿⣿⠇⠘⠐⢉⠁⢋⢰⡿⠻⣿⣿⣿⣿⣿⣿⣿⢸⣿⣿
⣿⣿⣿⣿⣿⣿⣿⡘⣿⣿⣿⣿⢸⣿⣿⢃⣾⣿⠿⠿⢿⣿⣶⣶⡙⣿⡟⣴⣶⣾⣿⠶⠇⠨⠶⢷⣌⠻⣿⣿⣿⣿⣿⢸⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣧⠋⢿⣿⣿⡼⠟⣡⠀⢈⢀⣤⠀⠀⠀⡉⢻⣷⣌⣴⣿⣿⠏⡁⣤⡄⠀⠀⢀⠀⢷⢠⣽⣿⢸⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⠘⣿⣿⣷⣾⣿⣇⢸⡀⠂⠀⠀⠀⢸⣾⣿⣿⣿⣿⣿⣿⡀⢊⠀⠀⠐⢸⣰⢆⣾⣿⣿⡿⢸⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣧⢹⣿⣿⣿⣿⣿⣆⠳⣄⣀⣀⣴⣿⣿⣿⣿⣿⣿⣿⣿⣷⣄⣀⣀⣤⣿⠏⣼⣿⣿⣿⠟⣼⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣧⡹⡿⢿⣿⣿⣿⣷⣌⠻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠏⢼⣿⣿⡿⢣⣾⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣦⣮⡹⢿⣿⣷⣄⢲⣿⣿⣿⣿⣿⣭⣭⣽⣿⣿⣿⣿⣿⠿⠛⠠⣾⠟⣫⣼⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣦⣝⠻⠀⣤⠄⠉⠛⠛⠛⠿⠟⠛⡛⠛⠋⢉⣔⣀⠀⢥⣴⣾⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⢋⡄⠉⢻⡏⡌⣼⡿⠈⠀⣙⡐⠀⢨⣿⡘⣆⢻⣿⠛⠂⡙⢿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠋⠈⠉⠉⠀⠻⠁⣰⣿⣷⣮⡙⢿⠛⣡⣶⣿⣷⣎⠘⡟⠃⠀⠙⠂⠙⢿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠟⣫⠄⠀⠀⠀⢀⣠⡆⠀⢻⣿⣿⣿⠁⠀⠀⢿⣿⣿⣿⠇⠀⠀⡀⠀⠀⠀⠀⠀⡙⢿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⠏⠐⢠⣬⡲⣄⢀⣰⣾⣿⡇⡀⢠⣍⣉⣥⡎⣴⡍⣮⣭⣭⣵⠠⢖⡁⢸⣦⡀⠀⢀⡴⢃⢻⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⢃⣾⣿⣦⡛⢿⢄⣾⣿⣿⣿⢳⣉⠈⢉⣉⡙⣧⠨⣰⡿⣭⡭⠭⢄⣹⡇⢸⣿⣿⡄⢪⣶⣿⣿⣌⢿⣿⣿
⣿⣿⣿⣿⣿⣿⡏⢿⣿⣿⣿⠏⣴⣾⣿⣿⣿⣿⠘⣿⣿⣶⣶⣶⣿⡇⣿⣷⣶⣶⣿⣿⣿⠟⢸⣿⣿⣿⣿⣦⡙⠿⠿⢋⣼⣿
⣿⣿⣿⣿⣿⣿⣿⣮⣭⣶⣿⣿⣿⣿⣿⣿⣿⣿⢰⣌⠻⣿⣿⣿⣿⡇⣿⣿⣿⣿⣿⢟⣥⣾⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠸⢿⣷⣮⣝⠻⢿⣷⣾⣿⠿⣋⣴⣿⠿⠟⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠐⠂⣿⣿⣿⣿⣶⠈⣭⢴⣿⣿⣿⣿⡔⠊⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⢸⡏⣛⢻⣿⣿⣿⢸⣿⠸⣿⣿⣿⢛⡙⣿⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣘⣡⣿⣆⠻⣿⡇⣿⣿⡆⠿⠟⣡⣿⣧⣙⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⣿⣿⠿⠿⠶⢠⣿⣿⣿⢰⣿⣿⣿⠿⢿⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡟⣱⣶⣶⣶⣿⣷⢸⣿⣿⣿⢰⣶⣶⣶⣾⣶⡸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡗⢻⣿⣿⣿⠹⠟⣸⣿⣿⣿⠘⣿⠟⣿⣿⣿⡇⢻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⣌⣛⣛⣉⣤⣾⣿⣿⣿⣿⣷⣄⣀⠙⠛⢛⣡⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿
